language: python
sudo: required
dist: xenial
before_install:
- chmod +x .travis/*.sh
matrix:
  include:
  - env: IMG="ubuntu1604"
    python:
    - 3.6
    install:
    - .travis/install-ubuntu.sh
    script:
    - .travis/build-py36.sh
    - .travis/release.sh
    - python setup.py test
deploy:
  provider: releases
  api_key:
    secure: BhYiumgaInTG0L+6oSVT5n0RQLus78V3NQejtCxnY5spPbTxsmP30KCAZkvzVedvOmZjssvDsz5KMPAxbPlgySQPZfal/cQSFv/9C/H5KI21MAOFXu1P+swyR83XGLgUH0DeCZV0NtTDsrpW/yuIoRLnWUqykS+V3j51vhH/IjrQeBhPGJR5G4CLE2/JdWdRlEzZOX/tjMpwXMxYv7mOcLlU8jfrEpAH0ahpINQxRm4rmvFrBgtQNpfBEHBh5tYlD47zrWloLJzreMxp07QZjM9xg/iftyjDd/y+wIkSbmQji9LRr/n1nAMmbB5h8ARHB6jaMqeJOQv7ugw0izSkUdWYv8y2AQI1ku25sanUEgbDCPUU/SzZGgtohx+Wm5CisYbU8LRUxX7VZQJ3dCqQbMAIlY4l047pePDLhllBCqI8XS6QU5ekirGrMWSbALBvT8do8QoOZ5y1I5owaA/uuYGvd80HYRGAHMtiMQEZrnM81HrceIUMRgrHp7bK+teM+3OwgC1NKMk6aWE41RKrheZ0MU7R/Nhk8X7EJq65DFiA/pnR2HDFfdgJdlizncG+lwO7RZNT4zrQAysmGgpnhVO63qDoB+kL2gCKI301NCLGSPf/81XTWMkD419in2nFpzYe9IYPh4dRsloZv/eaJrCZ6NokJJ/sBbPUMRW/x8A=
  file_glob: true
  file: release/*.gz
  skip_cleanup: true
  draft: true
  true:
    tags: true
    repo: vossen-adobe/user-sync-fork
    all_branches: true

